/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problem5;

import java.io.PrintWriter;
import java.io.File;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;

public class NewJFrame extends javax.swing.JFrame {

    
    /*
    Creating and assingning a initial value to all the data that
    will change when the submit button is pressed
    */
    int submits = 0;
    int sh = 0;
    int fi = 0;
    int pl = 0;
    int st = 0;
    int rp = 0;
    int pu = 0;
    int ar = 0;
    int sp = 0;
    int ot = 0;
    int h5 = 0;
    int h10 = 0;
    int h15 = 0;
    int h15plus = 0;
    String favgames = "";

    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        shooters = new javax.swing.JCheckBox();
        fighters = new javax.swing.JCheckBox();
        platformers = new javax.swing.JCheckBox();
        strategy = new javax.swing.JCheckBox();
        rpg = new javax.swing.JCheckBox();
        puzzle = new javax.swing.JCheckBox();
        arcade = new javax.swing.JCheckBox();
        sports = new javax.swing.JCheckBox();
        other = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        hours = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        games = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Please answer the following survey.");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("1 . What types of games do you like playing ( check all that apply )");

        shooters.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        shooters.setText("Shooters");

        fighters.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fighters.setText("Fighters");

        platformers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        platformers.setText("Platformers");

        strategy.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        strategy.setText("Strategy");

        rpg.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        rpg.setText("RPG");

        puzzle.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        puzzle.setText("Puzzle");

        arcade.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        arcade.setText("Arcade");

        sports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sports.setText("Sports");

        other.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        other.setText("Other");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("2. How many hours per week do you spend gaming?");

        hours.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hours.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "< 5 hours", "< 10 hours", "< 15 hours", "15+ hours" }));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("3. Enter a few games you're playing rignt now (separated by commas)");

        games.setColumns(20);
        games.setRows(5);
        jScrollPane1.setViewportView(games);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(146, 146, 146))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(platformers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(fighters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(shooters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(strategy, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(rpg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(puzzle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(arcade, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sports, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(other, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(shooters)
                    .addComponent(strategy)
                    .addComponent(arcade))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fighters)
                    .addComponent(rpg)
                    .addComponent(sports))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(platformers)
                    .addComponent(puzzle)
                    .addComponent(other))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            File file = new File("results.txt");

            /*
            Checking if the file results.txt exixts and 
            if it doesn't create the file
            */
            
            if (!file.exists()) {
                file.createNewFile();
            }

            /*
            Checking the options the user chose and adding it to the variable data
            */
            
            if (shooters.isSelected()) {
                sh++;
            }
            if (fighters.isSelected()) {
                fi++;
            }
            if (platformers.isSelected()) {
                pl++;
            }
            if (strategy.isSelected()) {
                st++;
            }
            if (rpg.isSelected()) {
                rp++;
            }
            if (puzzle.isSelected()) {
                pu++;
            }
            if (arcade.isSelected()) {
                ar++;
            }
            if (sports.isSelected()) {
                sp++;
            }
            if (other.isSelected()) {
                ot++;
            }
            String time = hours.getSelectedItem().toString();
            if ("< 5 hours".equals(time)) {
                h5++;
            }
            if ("< 10 hours".equals(time)) {
                h10++;
            }
            if ("< 15 hours".equals(time)) {
                h15++;
            }
            if ("15+ hours".equals(time)) {
                h15plus++;
            }
            favgames += games.getText();
            favgames += "\n";
            submits++;
            
            /*
            Calling the method that updates the file
            */
            
            updateFile();
            
            /*
            Setting the program to it's starting appearance
            */
            
            shooters.setSelected(false);
            fighters.setSelected(false);
            platformers.setSelected(false);
            strategy.setSelected(false);
            rpg.setSelected(false);
            puzzle.setSelected(false);
            arcade.setSelected(false);
            sports.setSelected(false);
            other.setSelected(false);
            hours.setSelectedIndex(0);
            games.setText("");

        } catch (IOException e) {
            System.out.println(e);
        }


    }//GEN-LAST:event_jButton1ActionPerformed

        /**
         *
         * @throws IOException
         */
        public void updateFile() throws IOException {
            BufferedWriter bw = null;
            try {
                File tempfile = new File("results.txt");
                FileWriter fw = new FileWriter(tempfile);
                bw = new BufferedWriter(fw);
                PrintWriter pw = new PrintWriter(bw);
                
                /*
                Using a print writer to overwrite the contents of the file 
                and using the example given make the file look like the example
                */
                
                pw.println("Number of surveys completed: " + submits);
                pw.println("\nQuestion 1:");
                pw.println("Shooters - " + sh + "\n"
                        + "Fighters - " + fi + "\n"
                        + "Platformers - " + pl + "\n"
                        + "Strategy - " + st + "\n"
                        + "RPG - " + rp + "\n"
                        + "Puzzle - " + pu + "\n"
                        + "Arcade - " + ar + "\n"
                        + "Sports - " + sp + "\n"
                        + "Other - " + ot + "");
                pw.println("\nQuestion 2:");
                pw.println("< 5 hours - " + h5 + "\n"
                        + "< 10 hours - " + h10 + "\n"
                        + "< 15 hours - " + h15 + "\n"
                        + "15+ hours - " + h15plus + "");
                pw.println("\nQuestion 3:");
                pw.println(favgames);
            } catch (IOException ioe) {
                ioe.printStackTrace(System.out);
            } finally {
                try {
                    if (bw != null) {
                        bw.close();
                    }
                } catch (IOException ioe) {
                    System.out.println("Error in closing the BufferedWriter");
                    ioe.printStackTrace(System.out);
                }
            }
        }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox arcade;
    private javax.swing.JCheckBox fighters;
    private javax.swing.JTextArea games;
    private javax.swing.JComboBox<String> hours;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox other;
    private javax.swing.JCheckBox platformers;
    private javax.swing.JCheckBox puzzle;
    private javax.swing.JCheckBox rpg;
    private javax.swing.JCheckBox shooters;
    private javax.swing.JCheckBox sports;
    private javax.swing.JCheckBox strategy;
    // End of variables declaration//GEN-END:variables
}
